# -*- coding: utf-8 -*-
"""Merge and clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5YVb84uFqC1z4i1TxgP1bNdx61bqRzd
"""

!pip install pypdf
!pip install pymupdf
!pip install fpdf

from pypdf import PdfReader, PdfWriter

def merge_pdfs(pdf_list, output_path):
    writer = PdfWriter()

    for pdf_file in pdf_list:
        reader = PdfReader(pdf_file)
        for page in reader.pages:
            writer.add_page(page)

    with open(output_path, "wb") as f_out:
        writer.write(f_out)

# Example usage
pdf_files = ['/content/English 1.pdf', '/content/English 2.pdf']
output_file = 'Emerge.pdf'

merge_pdfs(pdf_files, output_file)

from pypdf import PdfReader, PdfWriter

def merge_pdfs(pdf_list, output_path):
    writer = PdfWriter()

    for pdf_file in pdf_list:
        reader = PdfReader(pdf_file)
        for page in reader.pages:
            writer.add_page(page)

    with open(output_path, "wb") as f_out:
        writer.write(f_out)

# Example usage
pdf_files = ['/content/French 1.pdf', '/content/French 2.pdf']
output_file = 'Fmerge.pdf'

merge_pdfs(pdf_files, output_file)

import fitz
import re
from fpdf import FPDF


def clean_text(text):
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 12)

    def chapter_body(self, text):
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 10, text)

# Extract text, clean it, and write to PDF
def create_cleaned_pdf(input_pdf_path, output_pdf_path):
    # Load and extract text
    doc = fitz.open(input_pdf_path)
    cleaned_text = ""
    for page in doc:
        text = page.get_text()
        cleaned_text += clean_text(text) + "\n\n"

    # Create PDF
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.chapter_body(cleaned_text)
    pdf.output(output_pdf_path)
    print(f"Cleaned PDF saved as: {output_pdf_path}")

# Run the function
create_cleaned_pdf("/content/Emerge.pdf", "Cleaned_English.pdf")

import fitz
import re
from fpdf import FPDF


def clean_text(text):
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 12)

    def chapter_body(self, text):
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 10, text)

# Extract text, clean it, and write to PDF
def create_cleaned_pdf(input_pdf_path, output_pdf_path):
    # Load and extract text
    doc = fitz.open(input_pdf_path)
    cleaned_text = ""
    for page in doc:
        text = page.get_text()
        cleaned_text += clean_text(text) + "\n\n"

    # Create PDF
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.chapter_body(cleaned_text)
    pdf.output(output_pdf_path)
    print(f"Cleaned PDF saved as: {output_pdf_path}")

# Run the function
create_cleaned_pdf("/content/Fmerge.pdf", "Cleaned_French.pdf")

Api = "pcsk_g4i5v_Ds3ruCETwf5B516KCejmF2upXigJeLjPBhXWSUNq7f26AB33DFmfvoQ6ryaRyey"